### ISSUE TITLE
"Block" button not properly sized on a profil page

### ISSUE THREAD

**Issue by DiablosCorp** [gmodstore/gmodstore-issues#137]
![](http://image.noelshack.com/fichiers/2018/31/5/1533288437-bts.jpg)

Block button **isn't** properly sized in y on a profil page.

**Comment by Marcuzz** [comment]
Fixed

**Comment by DiablosCorp** [comment]
Not fixed yet (take a look at [this](https://beta.gmodstore.com/users/logoutphp) by example)
